// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Q5cI3h9Tze8LohEDh4qNjZd0EQvS_as',
    appId: '1:1040114170356:web:449bd0eb5c5410894b21a1',
    messagingSenderId: '1040114170356',
    projectId: 'loginsystem-b876f',
    authDomain: 'loginsystem-b876f.firebaseapp.com',
    databaseURL: 'https://loginsystem-b876f-default-rtdb.firebaseio.com',
    storageBucket: 'loginsystem-b876f.appspot.com',
    measurementId: 'G-J3WNLW5TCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufjanT5FYWbLrnasaz6tFBiiBM5dXzl4',
    appId: '1:1040114170356:android:e7ccc1009be36e704b21a1',
    messagingSenderId: '1040114170356',
    projectId: 'loginsystem-b876f',
    databaseURL: 'https://loginsystem-b876f-default-rtdb.firebaseio.com',
    storageBucket: 'loginsystem-b876f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PySZofnIHp3fCW9u5rWDUUpojteB8WU',
    appId: '1:1040114170356:ios:cb16b5892deb4bd94b21a1',
    messagingSenderId: '1040114170356',
    projectId: 'loginsystem-b876f',
    databaseURL: 'https://loginsystem-b876f-default-rtdb.firebaseio.com',
    storageBucket: 'loginsystem-b876f.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PySZofnIHp3fCW9u5rWDUUpojteB8WU',
    appId: '1:1040114170356:ios:cb16b5892deb4bd94b21a1',
    messagingSenderId: '1040114170356',
    projectId: 'loginsystem-b876f',
    databaseURL: 'https://loginsystem-b876f-default-rtdb.firebaseio.com',
    storageBucket: 'loginsystem-b876f.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Q5cI3h9Tze8LohEDh4qNjZd0EQvS_as',
    appId: '1:1040114170356:web:95aaccbf6cc0d7094b21a1',
    messagingSenderId: '1040114170356',
    projectId: 'loginsystem-b876f',
    authDomain: 'loginsystem-b876f.firebaseapp.com',
    databaseURL: 'https://loginsystem-b876f-default-rtdb.firebaseio.com',
    storageBucket: 'loginsystem-b876f.appspot.com',
    measurementId: 'G-FVSLT6NP8C',
  );
}
