// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTz7mDgabzX3MDvYG2nSFW4I6YgJpY1As',
    appId: '1:495066573169:web:35320184011f4d793f2ed0',
    messagingSenderId: '495066573169',
    projectId: 'aerobic-theorem-250612',
    authDomain: 'aerobic-theorem-250612.firebaseapp.com',
    databaseURL: 'https://aerobic-theorem-250612.firebaseio.com',
    storageBucket: 'aerobic-theorem-250612.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ1fvGXM35VBXD6bLTKpo9krXGq0vFXQs',
    appId: '1:495066573169:android:6b07c6bb8489166b3f2ed0',
    messagingSenderId: '495066573169',
    projectId: 'aerobic-theorem-250612',
    databaseURL: 'https://aerobic-theorem-250612.firebaseio.com',
    storageBucket: 'aerobic-theorem-250612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqDpn1pKNm1SJW7mBgx7oFpwF44KhDsY',
    appId: '1:495066573169:ios:50e92ce28460fcd73f2ed0',
    messagingSenderId: '495066573169',
    projectId: 'aerobic-theorem-250612',
    databaseURL: 'https://aerobic-theorem-250612.firebaseio.com',
    storageBucket: 'aerobic-theorem-250612.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqDpn1pKNm1SJW7mBgx7oFpwF44KhDsY',
    appId: '1:495066573169:ios:50e92ce28460fcd73f2ed0',
    messagingSenderId: '495066573169',
    projectId: 'aerobic-theorem-250612',
    databaseURL: 'https://aerobic-theorem-250612.firebaseio.com',
    storageBucket: 'aerobic-theorem-250612.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTz7mDgabzX3MDvYG2nSFW4I6YgJpY1As',
    appId: '1:495066573169:web:741db9799d8f66873f2ed0',
    messagingSenderId: '495066573169',
    projectId: 'aerobic-theorem-250612',
    authDomain: 'aerobic-theorem-250612.firebaseapp.com',
    databaseURL: 'https://aerobic-theorem-250612.firebaseio.com',
    storageBucket: 'aerobic-theorem-250612.appspot.com',
  );
}
